# This buildspec is run as a CI build on the acceptance-tests project itself.
# Note that currently this build does NOT need to succeed before the code is
# used as the acceptance tests of the Spire CD pipeline; it will always use the
# current commit of `main`.
version: 0.2
env:
  parameter-store:
    DOCKERHUB_USERNAME: /prx/DOCKERHUB_USERNAME
    DOCKERHUB_PASSWORD: /prx/DOCKERHUB_PASSWORD
    # Cypress
    CYPRESS_TEST_PRX_USER: /prx/test/meta.prx.org/TEST_PRX_USER
    CYPRESS_TEST_PRX_PASS: /prx/test/meta.prx.org/TEST_PRX_PASS
phases:
  pre_build:
    commands:
      - echo Logging in to Docker Hub...
      - echo $DOCKERHUB_PASSWORD | docker login --username $DOCKERHUB_USERNAME --password-stdin
  build:
    commands:
      - docker build --tag tests .
      - |
        docker run \
          --env CYPRESS_ID_HOST="id.staging.prx.tech" \
          --env CYPRESS_PUBLISH_HOST="publish.staging.prx.tech" \
          --env CYPRESS_FEEDER_HOST="podcasts.staging.prx.tech" \
          --env CYPRESS_AUGURY_HOST="inventory.staging.prx.tech" \
          --env CYPRESS_TEST_PRX_USER \
          --env CYPRESS_TEST_PRX_PASS \
          tests
